export interface Car {
    ownerId: string,
    mark: string,
    model: string,
    number: string,
    year: string,
    color: string,
    vin: string,
    engine_type: string,
    volume: string,
    power_ls: string,
    power_kvt: string,
    transmission: string,
    run: string,
    pts: string,
    sts: string,
    price: number,
    price_3d: number,
    price_5d: number,
    city: string,
    options?: [],
    imgSM?: string,
    photos?: []
}
