const tt = {
    carDelivery: "",
    casco: "98789",
childrenSeatPrice: "",
city: "New Jersey",
color: "#fafafa",
docs: [{}, {}, {}],
engine_type: "4",
error: {},
freePlace: "",
fuel: "",
id: "",
isAirbags: false,
isAuxCable: false,
isBluetooth: false,
isCamera: false,
isCarDelivery: false,
isChildrenSeat: false,
isConditioning: false,
isCreated: false,
isCruise: false,
isFreePlace: false,
isFuel: false,
isHeater: false,
isLosfix: false,
isMultimedia: false,
isNavigation: false,
isParktronic: false,
isRoofRack: false,
isSeatsHeat: false,
isSeatsVentilation: false,
mark: "Тесла",
model: "4гцгцгц",
number: "[eq",
osago: "878",
ownerId: 1,
photos: [{}, {}, {}],
power_kvt: "1111",
power_ls: "1000",
price: "700000",
price_3d: "700000",
price_5d: "700000",
pts: "1",
run: "1",
sts: "1",
transmission: "1",
vin: "77",
volume: "1",
year: "2022"}



const right = {
    city: "London",
    color: "white",
    docs: ["6"],
    engine_type: "gybrid",
    mark: "Toyota",
    model: "RAV4",
    number: "f6765kj",
    ownerId: "8",
    photos: [],
    power_kvt: "78",
    power_ls: "6788uh",
    price: 4000,
    price_3d: 3900,
    price_5d: 3800,
    pts: "pts4",
    run: "20999",
    sts: "sts5576",
    transmission: "Auto",
    vin: "876",
    volume: "3.2",
    year: "2017",
}
